version: '3'


services:


 meu_app:
  build: .
  ports:
    - "8080:8080"
  depends_on:
    - meu_db_validacao

 meu_db_validacao:
   image: postgres
   env_file:
       - .env
   volumes:
     - meu_postgres_data:/var/lib/postgresql/data
   ports:
     - "5432:5432"


volumes:

 meu_postgres_data:




