version: '3'


services:

 meu_db_validacao:

   image: postgres

   environment:

     POSTGRES_USER: ${POSTGRES_USER}

     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

     POSTGRES_DB: ${POSTGRES_DB}

   volumes:

     - meu_postgres_data:/var/lib/postgresql/data

   ports:

     - "5432:5432"


volumes:

 meu_postgres_data:




